# Generated by Django 5.0.2 on 2024-02-14 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(blank=True, max_length=250, null=True)),
                ('menu_display_title', models.CharField(blank=True, max_length=250, null=True)),
                ('disclaimer', models.CharField(blank=True, max_length=250, null=True)),
                ('image_path', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='email_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='location_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pickup_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='publishing_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='foodcategories',
            name='menu_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='available_for_online_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='default_tax_rate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='display_photo_path',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='poppable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='taxable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HungerPointApp.menu'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreivation', models.CharField(blank=True, max_length=250, null=True)),
                ('add_img_path', models.CharField(blank=True, max_length=250, null=True)),
                ('tag_c_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp')),
                ('tag_u_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Update_TimeStamp')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HungerPointApp.orders')),
            ],
        ),
    ]
