# Generated by Django 5.0.6 on 2024-06-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='fsc_certificate',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='formdata',
            name='fsc_certificate_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
