# Generated by Django 5.0.6 on 2024-06-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0002_formdata_fsc_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='menu_items',
            new_name='menu_item',
        ),
    ]
