# Generated by Django 5.0.2 on 2024-02-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0002_menu_address_delivery_enabled_address_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurent',
            name='every_day_time_list',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
