# Generated by Django 5.0.2 on 2024-02-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0003_alter_restaurent_every_day_time_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='abbreivation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
