# Generated by Django 5.0.6 on 2024-06-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0003_rename_menu_items_formdata_menu_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='FormData2',
        ),
        migrations.RenameField(
            model_name='formdata2',
            old_name='menu_item',
            new_name='menu_items',
        ),
    ]
