# Generated by Django 5.0.2 on 2024-02-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0004_alter_tag_abbreivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='abbreivation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
