# Generated by Django 5.0.6 on 2024-06-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0004_rename_formdata_formdata2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedboack_opt', models.CharField(blank=True, max_length=250, null=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('resume', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('resume_path', models.CharField(blank=True, max_length=250, null=True)),
                ('cover_letter', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('cover_letter_path', models.CharField(blank=True, max_length=250, null=True)),
                ('fsc_certificate', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('fsc_certificate_path', models.CharField(blank=True, max_length=250, null=True)),
                ('email_id', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('tag_c_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp')),
                ('tag_u_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Update_TimeStamp')),
                ('menu_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HungerPointApp.menuitems')),
            ],
        ),
        migrations.DeleteModel(
            name='FormData2',
        ),
    ]
