# Generated by Django 5.0.6 on 2024-06-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0005_formdatas_delete_formdata2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdatas',
            name='menu_items',
        ),
    ]
