# Generated by Django 5.0.2 on 2024-02-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0005_alter_tag_abbreivation_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=250, null=True)),
                ('c_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create_TimeStamp')),
                ('u_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Update_TimeStamp')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('restaurent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HungerPointApp.restaurent')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HungerPointApp.userrole'),
        ),
    ]
