# Generated by Django 5.0.2 on 2024-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HungerPointApp', '0007_rename_order_date_orders_order_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='f_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='l_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permission_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
